### ISSUE TITLE
Add system role 'everyone'

### ISSUE THREAD

**Issue by darh** [crusttech/crust#55]
- [x] prepopulate `sys_roles` table with `everyone` role (we can simly use 1 for it's ID)
 - [x] auto append role to each user (when authenticated)
 - [x] preset some basic permissions (access to both services)

The main goal is to ease initial setup and to prevent a lockout of first users on the system.

**Comment by darh** [comment]
@titpetric comments?

**Comment by titpetric** [comment]
So, `everyone` should be a sticky role, all users should be members of it, and by default that role has access to compose and messaging? LGTM

**Comment by darh** [comment]
Also added `admin`/`Administators` role with all permissions set to allow.
