### ISSUE TITLE
Clarify contribution rules, DCO

### ISSUE THREAD

**Issue by titpetric** [crusttech/crust#70]
- [x] Contribution rules, examples:
    - https://github.com/openfaas/faas/blob/master/CONTRIBUTING.md
    - https://github.com/go-gitea/gitea/blob/master/CONTRIBUTING.md
- [x] DCO
    - easiest option: https://github.com/integration/dco
    - possible enforcement bot: https://github.com/alexellis/derek

We already discussed the DCO a bit. Adding this issue as a discussion point, so we can decide the scope of the contributions document (we have a wiki with guidelines already), and if we can automate the DCO parts using the derek project (or something else).

**Comment by titpetric** [comment]
Here's a more explicit contribution guide layout I'd like to enforce. Some of this has been added to the Issues/PR templates, but should be extended in the repository & wiki.

- https://github.com/leon-ai/leon/blob/develop/.github/CONTRIBUTING.md

**Comment by alexiskraft** [comment]
@titpetric This is very much a short term requirement!

**Comment by titpetric** [comment]
DCO and contribution guides added to master repo, enforcing signed commits from this point on.
