### ISSUE TITLE
Write a cli tool to reset system roles and it's permission

### ISSUE THREAD

**Issue by darh** [crusttech/crust#89]
We need a tool that:
 - resets/recreates `Administrators` (ID:`2`) and `Everyone` (ID:`1`) roles if they do not exist
 - resets permissions (admin role gets all permissions set to allow, everyone role gets basics -- see .sql files )
 - assigns all OR specific users (by ID or email) to a specific role.

See `cmd/system-cli` code and follow the pattern.

(maybe also #88)

**Comment by titpetric** [comment]
Closing, track issue in #100
