### ISSUE TITLE
Github Issue/PR templates

### ISSUE THREAD

**Issue by titpetric** [crusttech/crust#91]
Example:

- https://github.com/gonum/gonum/tree/master/.github

We already have a wiki page (issues reporting flow), which we can reference from here. I'd also like to encourage more content complete feature requests (see feature request template).

**Comment by titpetric** [comment]
I added a minimal subset of issue reporting templates and a PR one.  Improve with time as needed.

**Comment by darh** [comment]
Can you please point me to this templates, cant find them...

**Comment by titpetric** [comment]
They are in the /.github folder.
