### ISSUE TITLE
internal/rules package and other permissioning cleanup

### ISSUE THREAD

**Issue by darh** [crusttech/crust#96]
See #90 

Other things that are not needed anymore:
 - [ ] The package should be in singular form
 - [x] `rules.Operation` and `rules.OperationGroup` should be removed, we're using operation as a string everywhere
 - [x] `rules.Scope` should be removed
 - [x] `*.perms.gen.go files`
 - [ ] Majority of related `*JSON` structs and funcs
 - [ ] `system/service/validation.go` could be moved under internal.

More? Thoughts?

**Comment by titpetric** [comment]
- no need to rename pkg to singular (it's a special case like "types", "metrics", ...)
- the JSON is only relevant for Resource, should be done with #78, keep `Access` `*JSON`
- no need to move validation, it's private and system is the only entrypoint (vote: keep it there)

**Comment by titpetric** [comment]
The rest is implemented.
